site_name: Embedded Tester Protocol Library

docs_dir: src
site_url: https://etplib.readthedocs.io/
repo_url: https://github.com/jabezwinston/etplib-python
repo_name: etplib-python
copyright: Copyright &copy; 2024 Jabez Winston

theme:
  name: readthedocs
  highlightjs: true

nav:
  - Introduction: index.md
  - API reference guide:
    - General: api/general.md
    - GPIO: api/gpio.md
    - ADC: api/adc.md
    - PWM: api/pwm.md
    - I2C: api/i2c.md
    - SPI: api/spi.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          paths: [../..]
          options:
            docstring_options:
                ignore_init_summary: true
            # docstring_section_style: numpy
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            preload_modules: [mkdocstrings]
            relative_crossrefs: true
            scoped_crossrefs: true
            separate_signature: true
            show_bases: false
            show_inheritance_diagram: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true
